service: todo-api-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: david-mobapp 
  region: eu-north-1
  iam:
    role: arn:aws:iam::626646945997:role/lectures-cloud

plugins: 
    - serverless-webpack

package:
    individually: true

functions:
  getTodos:
    handler: functions/getTodos/index.handler
    events:
      - httpApi:
          path: '/todos'
          method: GET
  postTodo:
   handler: functions/postTodo/index.handler
   events:
      - httpApi:
          path: '/todos'
          method: POST
  deleteTodo:
    handler: functions/deleteTodo/index.handler
    events:
      - httpApi:
          path: '/todos/{id}'
          method: DELETE
  editTodo:
    handler: functions/editTodo/index.handler
    events:
      - httpApi:
          path: '/todos/{id}'
          method: PATCH        
          

resources:
  Resources:
    todosDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos-db
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
